
training_args:
  batch_size: 16
  num_epochs: 1000
  init_learning_rate: 1.0e-4
  min_learning_rate: 1.0e-6
  early_stop_patience: 10
  test_frequency: 5

model_args:
  in_channels: 2
  num_latent_channels: 8
  channels: [16, 32, 64, 128]
  padding: "periodic"

optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-8
  betas: [0.9, 0.999]
