training_args:
  ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
  time_step_info:
    start_time: 1000
    num_steps: 250
    skip_steps: 2
normalize_data: false
test_args:
  pars_low:
    ids:
      - 46
    time_step_info:
      start_time: 1000
      num_steps: 250
      skip_steps: 2
norm_mean:
  - 1.766131330172005e-8
  - 1.422475315049354e-8
parameter_dimensions: ~
state_dimensions:
  height: 128
  channels: 2
  width: 128
pars_max:
  - 1.0
state_variables:
  - "velocity_x"
  - "velocity_y"
pars_min:
  - 0.0
with_mask: false
norm_std:
  - 0.7129140811183516
  - 0.6955684386129051
data_folder: "data/kolmogorov_128"
