training_args:
  early_stop_patience: 10
  num_warmup_steps: 10
  num_test_paths: 5
  batch_size: 8
  test_frequency: 10
  num_test_sde_steps: 50
  min_learning_rate: 1.0e-6
  num_epochs: 1000
  max_learning_rate: 0.0001
interpolant_args:
  gamma_multiplier: 0.1
  coefs: []
  alpha: "linear"
  gamma: "linear"
  beta: "quadratic"
model_args:
  use_attention_in_layer:
    - false
    - false
    - false
    - false
    - true
  channels:
    - 16
    - 32
    - 64
    - 128
  in_channels: 2
  padding: "periodic"
  out_channels: 2
  len_history: 2
  embedding_dims: 128
  pars_dim: 0
  num_heads: 4
  projection: "divergence_free"
  attention_type: "DiT"
  attention_embedding_dims: 64
  model_type: "conv_next_u_net"
diffusion_args:
  multiplier: 0.1
  type: "linear"
optimizer_args:
  betas:
    - 0.9
    - 0.999
  learning_rate: 0.0001
  weight_decay: 1.0e-8
