training_args:
  init_learning_rate: 0.0001
  early_stop_patience: 10
  batch_size: 16
  test_frequency: 5
  min_learning_rate: 1.0e-6
  num_epochs: 1000
model_args:
  num_latent_channels: 8
  in_channels: 2
  padding: "periodic"
  channels:
    - 16
    - 32
    - 64
    - 128
optimizer_args:
  betas:
    - 0.9
    - 0.999
  learning_rate: 0.0001
  weight_decay: 1.0e-8
