training_args:
  init_learning_rate: 0.0001
  early_stop_patience: 10
  num_test_paths: 5
  batch_size: 8
  test_frequency: 50
  num_test_sde_steps: 100
  min_learning_rate: 1.0e-6
  num_epochs: 1000
interpolant_args:
  gamma_multiplier: 0.1
  alpha: "linear"
  gamma: "linear"
  beta: "quadratic"
model_args:
  embedding_dims: 128
  attention_type: "DiT"
  use_attention_in_layer:
    - false
    - false
    - false
    - false
  padding: "periodic"
  num_heads: 4
  channels:
    - 16
    - 32
    - 64
    - 128
  attention_embedding_dims: 64
  len_history: 2
  projection: ~
diffusion_args:
  multiplier: 0.1
  type: "follmer_optimal"
optimizer_args:
  betas:
    - 0.9
    - 0.999
  learning_rate: 0.0001
  weight_decay: 1.0e-8
