
data_folder: "data/128_iso"

state_variables:
  - velocity_x
  - velocity_y
  - velocity_z
  - pressure

state_dimensions:
  height: 64
  width: 128
  channels: 4

parameter_dimensions: null

with_mask: false

# Training and test IDs
training_args:
  # ids: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40]
  ids: [9, 10, 11, 12, 13, 19, 20, 21, 22, 23, 24, 25, 26]
  # ids: [10, 11, 12, 13, 14, 15, 16, 17, 18]
  time_step_info:
    start_time: 1
    num_steps: 100
    skip_steps: 2

test_args:
  z_extrapolation:
    ids: [0, 1, 2]
    time_step_info:
      start_time: 1
      num_steps: 60
      skip_steps: 2




# Normalization parameters
# velocity_x: mean = -0.054618, std = 0.539194
# velocity_y: mean = -0.385225, std = 0.710318
# velocity_z: mean = -0.255757, std = 0.510352
# pressure: mean = 0.033446, std = 0.258235
norm_mean: [-0.054618, -0.385225, -0.255757, 0.033446]
norm_std: [0.539194, 0.710318, 0.510352, 0.258235]


