training_args:
  ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
  time_step_info:
    start_time: 500
    num_steps: 200
    skip_steps: 4
normalize_data: false
test_args:
  pars_low:
    ids:
      - 10
    time_step_info:
      start_time: 540
      num_steps: 50
      skip_steps: 4
norm_mean:
  - 1.766131330172005e-8
  - 1.422475315049354e-8
parameter_dimensions: ~
state_dimensions:
  height: 64
  channels: 2
  width: 64
pars_max:
  - 1.0
state_variables:
  - "velocity_x"
  - "velocity_y"
pars_min:
  - 0.0
with_mask: false
norm_std:
  - 0.7129140811183516
  - 0.6955684386129051
data_folder: "data/periodic_box_turbulence_data_64.jld2"
