training_args:
  ids:
    - 10
    - 11
    - 12
    - 13
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
  time_step_info:
    start_time: 1000
    num_steps: 150
    skip_steps: 2
normalize_data: true
test_args:
  pars_var:
    ids:
      - 14
      - 15
    time_step_info:
      start_time: 300
      num_steps: 100
      skip_steps: 2
  pars_low:
    ids:
      - 0
      - 2
      - 4
      - 6
      - 8
    time_step_info:
      start_time: 1000
      num_steps: 60
      skip_steps: 2
  pars_high:
    ids:
      - 82
      - 84
      - 86
      - 88
      - 90
    time_step_info:
      start_time: 1000
      num_steps: 60
      skip_steps: 2
norm_mean:
  - 0.444969
  - 0.000299
  - 0.000586
parameter_dimensions:
  Reynolds Number: 1
state_dimensions:
  height: 64
  channels: 3
  width: 128
pars_max:
  - 1000.0
state_variables:
  - "velocity_x"
  - "velocity_y"
  - "pressure"
pars_min:
  - 100.0
with_mask: true
norm_std:
  - 0.206128
  - 0.206128
  - 0.003942
data_folder: "data/128_inc/128_inc"
