training_args:
  init_learning_rate: 0.0001
  early_stop_patience: 10
  num_test_paths: 5
  batch_size: 8
  test_frequency: 20
  num_test_sde_steps: 50
  min_learning_rate: 1.0e-6
  num_epochs: 1000
interpolant_args:
  gamma_multiplier: 0.1
  alpha: "linear"
  gamma: "linear"
  beta: "quadratic"
model_args:
  mlp_ratio: 4
  dropout_rate: 0.1
  channels:
    - 8
  depth: 6
  in_channels: 8
  padding: "periodic"
  out_channels: 8
  embedding_dropout_rate: 0.1
  len_history: 2
  embedding_dims: 128
  patch_size: 1
  pars_dim: 0
  num_heads: 4
  projection: ~
  model_type: "diffusion_transformer"
diffusion_args:
  multiplier: 0.1
  type: "linear"
optimizer_args:
  betas:
    - 0.9
    - 0.999
  learning_rate: 0.0001
  weight_decay: 1.0e-8
